@echo off
echo Adding VITE_FIREBASE_API_KEY...
call npx vercel env add VITE_FIREBASE_API_KEY production,preview,development --value AIzaSyD8ADVYW9w2eMJN1L8_9VG7tP2ddDB4iGU --yes --force --no-sensitive
echo Adding VITE_FIREBASE_AUTH_DOMAIN...
call npx vercel env add VITE_FIREBASE_AUTH_DOMAIN production,preview,development --value gym-desk-b7301.firebaseapp.com --yes --force --no-sensitive
echo Adding VITE_FIREBASE_PROJECT_ID...
call npx vercel env add VITE_FIREBASE_PROJECT_ID production,preview,development --value gym-desk-b7301 --yes --force --no-sensitive
echo Adding VITE_FIREBASE_STORAGE_BUCKET...
call npx vercel env add VITE_FIREBASE_STORAGE_BUCKET production,preview,development --value gym-desk-b7301.firebasestorage.app --yes --force --no-sensitive
echo Adding VITE_FIREBASE_MESSAGING_SENDER_ID...
call npx vercel env add VITE_FIREBASE_MESSAGING_SENDER_ID production,preview,development --value 803308664122 --yes --force --no-sensitive
echo Adding VITE_FIREBASE_APP_ID...
call npx vercel env add VITE_FIREBASE_APP_ID production,preview,development --value 1:803308664122:web:fbcdb89553bcd8097f8c03 --yes --force --no-sensitive
echo Adding VITE_FIREBASE_MEASUREMENT_ID...
call npx vercel env add VITE_FIREBASE_MEASUREMENT_ID production,preview,development --value G-HZ5FGCBGRL --yes --force --no-sensitive
echo Adding VITE_FIREBASE_DATABASE_URL...
call npx vercel env add VITE_FIREBASE_DATABASE_URL production,preview,development --value https://gym-desk-b7301-default-rtdb.asia-southeast1.firebasedatabase.app --yes --force --no-sensitive
echo Adding VITE_USE_FIREBASE_EMULATOR...
call npx vercel env add VITE_USE_FIREBASE_EMULATOR production,preview,development --value false --yes --force --no-sensitive
echo Done adding all variables!
